# Generated by Django 3.2.13 on 2022-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, verbose_name='User Email')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Your phone')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Your Address')),
                ('financial_help', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Need Financial Help')),
                ('need_job', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Need Job')),
                ('need_training', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Need Training')),
                ('know_job', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Know a Job Vacancy')),
                ('driving', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Have Driving Licence')),
                ('medical', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Need Medical Insurance')),
                ('single', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You are Single')),
                ('volunteer', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, verbose_name='You Can be Volunteer')),
            ],
        ),
    ]
