# Generated by Django 4.1.7 on 2023-02-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220829_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
