# Generated by Django 4.1.7 on 2023-03-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
