# Generated by Django 3.2.13 on 2022-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='financial_help',
            field=models.BooleanField(default=True, verbose_name='Finance Help'),
        ),
    ]
