# Generated by Django 3.2.13 on 2022-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_myclubuser_financial_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='driving',
            field=models.BooleanField(default=False, verbose_name='Do you have a driving License'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='know_job',
            field=models.BooleanField(default=False, verbose_name='Know a job opening in your team/company/business'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='medical',
            field=models.BooleanField(default=False, verbose_name='Need medical help'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='need_job',
            field=models.BooleanField(default=False, verbose_name='Need Job'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='need_training',
            field=models.BooleanField(default=False, verbose_name='Need Training/Monitering'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='single',
            field=models.BooleanField(default=False, verbose_name='Single'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='volunteer',
            field=models.BooleanField(default=False, verbose_name='Willing to volunteer'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='financial_help',
            field=models.BooleanField(default=False, verbose_name='Need Finance Help'),
        ),
    ]
