# Generated by Django 3.2.13 on 2022-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220603_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Your phone'),
        ),
    ]
