# Generated by Django 3.2.13 on 2022-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_myclubuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Your Address'),
        ),
    ]
