# Generated by Django 4.1.7 on 2023-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20220623_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='driving',
            field=models.BooleanField(default='', verbose_name='Have Driving Licence'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='financial_help',
            field=models.BooleanField(default='', verbose_name='Need Financial Help'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='know_job',
            field=models.BooleanField(default='', verbose_name='You Know a Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='medical',
            field=models.BooleanField(default='', verbose_name='Need Medical Insurance'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='need_job',
            field=models.BooleanField(default='', verbose_name='Need Job'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='need_training',
            field=models.BooleanField(default='', verbose_name='Need Training'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='single',
            field=models.BooleanField(default='', verbose_name='Single'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='volunteer',
            field=models.BooleanField(default='', verbose_name='Can be Volunteer'),
        ),
    ]
