# Generated by Django 4.1.7 on 2023-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_myclubuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='birthdate',
            field=models.DateField(default='YYYY-MM-DD', verbose_name='Birthdate'),
        ),
    ]
